name: Build & Release Composer Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer Dependencies
        run: composer install --no-dev --prefer-dist --no-progress

      - name: Install YAK Pro Php Obfuscator
        run: |
          git clone https://github.com/pk-fr/yakpro-po.git yakpro-po
          cd yakpro-po
          git clone https://github.com/nikic/PHP-Parser.git --branch 4.x
          cd ..

      - name: Run Build Script
        run: bash scripts/build.sh

      - name: Read Version from File
        id: read_version
        run: echo "new_tag=$(cat version.txt)" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.read_version.outputs.new_tag }}
          name: Release ${{ steps.read_version.outputs.new_tag }}
          files: build/package.zip
